### ISSUE TITLE
Lydia plugin causing issues with anonymous admins

### ISSUE THREAD

**Issue by unixandria-xda** [UsergeTeam/Userge-Plugins#166]
In a group I'm an anonymous admin in, the Lydia plugin keeps spitting out the following:
```
Traceback (most recent call last):
  File "/home/userbot/Userge/userge/core/methods/decorators/raw_decorator.py", line 314, in template
    await func(types.bound.Message.parse(
  File "/home/userbot/Userge/userge/plugins/unofficial/lydia.py", line 159, in lydia_ai_chat
    data = ACTIVE_CHATS.get(message.from_user.id)
AttributeError: 'NoneType' object has no attribute 'id'

```

**Comment by Krishna-Singhal** [comment]
Hmm that account is now deleted that why this error
