### ISSUE TITLE
Issue with .gcopy and copying folders

### ISSUE THREAD

**Issue by Xazmah** [UsergeTeam/Userge-Plugins#259]
I'm facing an issue when trying to copy folders (folders are stored in Team Drives I have access to) using .gcopy, copying files (stored in Team Drives as well) working just fine but can't copy folders (was working fine before v1)

Here's the logs

```
Traceback (most recent call last):
    File "/app/userge/plugins/misc/gdrive/__main__.py", line 480, in _copy
      dir_id = self._create_drive_dir(drive_file['name'], self._parent_id)
    File "/app/userge/plugins/misc/gdrive/__main__.py", line 287, in _create_drive_dir
      self._set_permission(file_id)
    File "/app/userge/plugins/misc/gdrive/__main__.py", line 178, in _set_permission
      self._service.permissions().create(fileId=file_id, body=permissions,
    File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
      return wrapped(*args, **kwargs)
    File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/http.py", line 937, in execute
      raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v3/files/0bqh7jmqjMMZDNXm4OvMilVMKvvQi2kPw/permissions?supportsTeamDrives=true&alt=json returned "Bad Request. User message: """. Details: "[{'domain': 'global', 'reason': 'publishOutNotPermitted', 'message': 'Bad Request. User message: ""'}]">
```

**Comment by rking32** [comment]
`.gup` works fine?

**Comment by Xazmah** [comment]
Yeah .gup is uploading files but showing the same error in logs
