### ISSUE TITLE
[ERROR] Speedtest

### ISSUE THREAD

**Issue by alamia442** [UsergeTeam/Userge-Plugins#296]
[12-Jun-22 09:29:56 - ERROR] - userge.core.methods.decorators.raw_decorator - cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/app/userge/core/methods/decorators/raw_decorator.py", line 327, in template
    await func(types.bound.Message.parse(
  File "/app/userge/plugins/tools/speedtest/__main__.py", line 36, in speedtst
    path = await pool.run_in_thread(wget.download)(result['share'])
  File "/app/userge/core/ext/pool.py", line 37, in wrapper
    return await loop.run_in_executor(_EXECUTOR, partial(func, *args, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.9/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/local/lib/python3.9/urllib/request.py", line 237, in urlretrieve
    url_type, path = _splittype(url)
  File "/usr/local/lib/python3.9/urllib/parse.py", line 1040, in _splittype
    match = _typeprog.match(url)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by rking32** [comment]
fixed in https://github.com/UsergeTeam/Userge-Plugins/commit/ef6916b0628ec982c89d1e76baf3661424e33c20
